version: "3.8"

services:
  frontend:
    build: .
    container_name: headless-nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WORDPRESS_API_URL=${NEXT_PUBLIC_WORDPRESS_API_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    restart: always
